import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import './TermsAndPrivacy.css';

const TermsAndPrivacy = () => {
  const location = useLocation();
  const isTerms = location.pathname === '/terms';

  return (
    <div className="tap-page">
      <div className="tap-navbar">
        <div className="tap-brand">
          <div className="tap-brand-icon">✈</div>
          <span>AI<em>Trip</em></span>
        </div>
        <Link to="/signup" className="tap-back">← Back to Signup</Link>
      </div>

      <div className="tap-content">
        <div className="tap-header">
          <span className="tap-badge">{isTerms ? '📄 Legal' : '🔒 Privacy'}</span>
          <h1>{isTerms ? 'Terms of Service' : 'Privacy Policy'}</h1>
          <p>Last updated: March 2026 · AI Trip Planner · Vignan University</p>
        </div>

        {isTerms ? (
          <div className="tap-body">
            <div className="tap-section">
              <h2>1. Acceptance of Terms</h2>
              <p>By accessing and using AI Trip Planner ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. This is a Final Year Project developed at Vignan University for educational purposes.</p>
            </div>

            <div className="tap-section">
              <h2>2. Use of the Service</h2>
              <p>You may use the Service to generate AI-powered travel itineraries for personal, non-commercial use. You agree not to:</p>
              <ul>
                <li>Use the Service for any unlawful purpose</li>
                <li>Attempt to gain unauthorized access to our systems</li>
                <li>Abuse or misuse the AI generation features</li>
                <li>Share your account credentials with others</li>
                <li>Spam or overload the trip generation feature</li>
              </ul>
            </div>

            <div className="tap-section">
              <h2>3. AI-Generated Content</h2>
              <p>Trip itineraries are generated by AI (GPT-4o-mini) and are for informational purposes only. We do not guarantee the accuracy, completeness, or suitability of any generated content. Always verify travel information with official sources before booking.</p>
            </div>

            <div className="tap-section">
              <h2>4. Account Responsibility</h2>
              <p>You are responsible for maintaining the confidentiality of your account and password. You agree to notify us immediately of any unauthorized use of your account.</p>
            </div>

            <div className="tap-section">
              <h2>5. Intellectual Property</h2>
              <p>The AI Trip Planner platform, including its design, code, and features, is the intellectual property of the project team at Vignan University. Trip plans generated are provided to you for personal use.</p>
            </div>

            <div className="tap-section">
              <h2>6. Limitation of Liability</h2>
              <p>The Service is provided "as is" without warranties of any kind. We shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service, including reliance on AI-generated travel information.</p>
            </div>

            <div className="tap-section">
              <h2>7. Changes to Terms</h2>
              <p>We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>
            </div>

            <div className="tap-section">
              <h2>8. Contact</h2>
              <p>For questions about these Terms, contact us through Vignan University's Department of Computer Science & Engineering.</p>
            </div>
          </div>
        ) : (
          <div className="tap-body">
            <div className="tap-section">
              <h2>1. Information We Collect</h2>
              <p>When you use AI Trip Planner, we collect:</p>
              <ul>
                <li><strong>Account information:</strong> Name, email address when you register</li>
                <li><strong>Trip data:</strong> Destination, duration, budget, and companions for trip generation</li>
                <li><strong>Usage data:</strong> Trip history, favourites, and preferences</li>
                <li><strong>Authentication data:</strong> Managed securely by Supabase</li>
              </ul>
            </div>

            <div className="tap-section">
              <h2>2. How We Use Your Information</h2>
              <p>We use the information we collect to:</p>
              <ul>
                <li>Generate personalized AI travel itineraries</li>
                <li>Save and display your trip history</li>
                <li>Improve our ML model's trip satisfaction predictions</li>
                <li>Maintain and improve the Service</li>
                <li>Send account-related notifications (password resets, etc.)</li>
              </ul>
            </div>

            <div className="tap-section">
              <h2>3. Data Storage</h2>
              <p>Your data is stored securely using Supabase (PostgreSQL database) with Row Level Security (RLS) enabled. This means only you can access your trip data — other users cannot see your information.</p>
            </div>

            <div className="tap-section">
              <h2>4. Third-Party Services</h2>
              <p>We use the following third-party services:</p>
              <ul>
                <li><strong>Supabase:</strong> Authentication and database storage</li>
                <li><strong>OpenAI (via Bytez):</strong> AI trip generation (your trip data is sent to generate itineraries)</li>
                <li><strong>Google OAuth:</strong> Optional social login</li>
              </ul>
            </div>

            <div className="tap-section">
              <h2>5. Data Retention</h2>
              <p>Your trip data is retained as long as your account is active. You can delete individual trips or your entire account at any time through the Settings page. Account deletion permanently removes all your data.</p>
            </div>

            <div className="tap-section">
              <h2>6. Your Rights</h2>
              <p>You have the right to:</p>
              <ul>
                <li>Access all data we hold about you</li>
                <li>Delete your account and all associated data</li>
                <li>Update your personal information at any time</li>
                <li>Export your trip history (via PDF download)</li>
              </ul>
            </div>

            <div className="tap-section">
              <h2>7. Security</h2>
              <p>We implement industry-standard security measures including JWT authentication, Row Level Security, HTTPS encryption, and input validation. However, no method of transmission over the internet is 100% secure.</p>
            </div>

            <div className="tap-section">
              <h2>8. Contact</h2>
              <p>For privacy concerns, contact us through Vignan University's Department of Computer Science & Engineering.</p>
            </div>
          </div>
        )}

        <div className="tap-footer">
          <Link to="/signup" className="tap-cta">← Back to Signup</Link>
          <Link to={isTerms ? '/privacy' : '/terms'} className="tap-switch">
            {isTerms ? 'View Privacy Policy →' : 'View Terms of Service →'}
          </Link>
        </div>
      </div>
    </div>
  );
};

export default TermsAndPrivacy;